stages:
 - update
update_project:
 stage: update
 script:
   - cd ${PROJECT_NAME}-main
   - xcrun agvtool next-version -all
   - pod install
   - xcodebuild clean -workspace ${PROJECT_NAME}.xcworkspace -scheme ${PROJECT_SCHEME}
   - xcodebuild build -workspace ${PROJECT_NAME}.xcworkspace -scheme ${PROJECT_SCHEME} PROVISIONING_PROFILE=c52980e0-cd32-4e7b-b9df-54974bc03f98
   - xcodebuild archive -workspace ${PROJECT_NAME}.xcworkspace -scheme sweatgen -archivePath ${PROJECT_NAME}.xcarchive
   - xcodebuild -exportArchive -archivePath ${PROJECT_NAME}.xcarchive -exportPath ./ -exportOptionsPlist ExportOptions.plist
   - /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support/altool --upload-app -f sweatgen.ipa -u ${EMAIL_APP_STORE} -p ${PASSWORD_APP_STORE}
   - git add ${PROJECT_NAME}/Config/Info.plist
   - git add ${PROJECT_NAME}.xcodeproj/project.pbxproj
   - git commit -m "update version from gitlab runner "
   - git push http://username:token@git.gits.id/${PROJECT_NAME}.git HEAD:master
 only:
   refs:
     - master
     - merge_requests
   variables:
     - $CI_COMMIT_MESSAGE =~ /\Q[build]\E/
 tags:
   - /^ios-.*$/
