disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- closure_parameter_position
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

nesting:
    type_level: 3

